name: Test PHP

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version to use'
        required: false
        type: string
        default: '8.3'
      wp-version:
        description: 'WordPress version to test against'
        required: false
        type: string
        default: 'latest'
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  test-php:
    name: Run PHP tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      WP_TESTS_DIR: /tmp/wordpress-tests-lib
      WP_CORE_DIR: /tmp/wordpress/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: ${{ inputs.php-version }}
          tools: composer
          extensions: mysqli
          coverage: pcov

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y subversion default-mysql-client

      - name: Install Composer dependencies
        run: composer update

      - name: Setup WordPress test environment
        run: |
          rm -rf $WP_TESTS_DIR $WP_CORE_DIR
          bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 ${{ inputs.wp-version }}

      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false
